CarHire.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarHire.WebUI.Controllers
{
    public class NavController : Controller
    {
        // GET: Nav
        public PartialViewResult Menu()
        {
            return PartialView();
        }
    }
}

CarHire.WebUI/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarHire.Domain.Abstract;
using CarHire.Domain.Entities;
namespace CarHire.WebUI.Controllers
{
    public class UsersController : Controller
    {
        private IUserRepository repository;
        public UsersController(IUserRepository repo)
        {
            this.repository = repo;
        }
        // GET: Users
        public ActionResult Holder()
        {
            if (Session["Category"] == null) 
            {
                    return RedirectToAction("Index", "Home");
                    
            }
            else if (Session["Category"].Equals("Kierownik"))
            {
                return View(repository.Users);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        public ViewResult SignIn()
        {
            return View("New", new User());

        }
        public ActionResult Create()
        {
            if (Session["Category"] == null) 
            {
                return RedirectToAction("Index", "Home");
            }else if (Session["Category"].Equals("Kierownik"))
            {
                return View("Edit", new User());
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
        public ViewResult Edit(int userId)
        {
            User user = repository.Users.FirstOrDefault(p => p.UserID == userId);
            return View(user);
        }
        [HttpPost]
        public ActionResult New(User user)
        {
            if (ModelState.IsValid)
            {
                if (Session["Category"] == null)
                {
                    repository.NewUser(user, "Klient");
                    return RedirectToAction("Index", "Home");
                }
                else if (Session["Category"].Equals("Kierownik"))
                {
                    repository.NewUser(user, "Pracownik");
                    return RedirectToAction("Index", "Home");
                }else
                    return RedirectToAction("Index", "Home");
            }
            else
            {
                return View(user);
            }
        }
        [HttpPost]
        public ActionResult Edit(User user)
        {
            if (ModelState.IsValid)
            {
                repository.SaveUser(user);
                TempData["message"] = string.Format("Zapisano {0}", user.Name);
                return RedirectToAction("Index","Home");
            }
            else
            {
                return View(user);
            }
        }
        [HttpPost]
        public ActionResult Delete(int UserId)
        {
            User deletedUser = repository.DeleteUser(UserId);
            if (deletedUser != null)
            {
                TempData["massage"] = string.Format("Usunięto {0}", deletedUser.Name);
            }
            return RedirectToAction("Index","Home");
        }
    }

}

CarHire.WebUI/Views/Shared/CarSummary.cshtml
@model CarHire.Domain.Entities.Car

<div class="well">

<h3><p><strong>@Model.Brand @Model.Model</strong></p></h3>
<h3>
    @if (Model.Hired == true)
    {
        <span class="pull-right label label-danger">Wypożyczony</span>
    }
    else
    {
        if (Session["LogedUserID"] != null)
        {
            @Html.ActionLink("Wypożycz", "Create", "Rental", new { carId = Model.CarID }, new { @class = "pull-right btn btn-default btn-xs" })
        }
        else
        {
            @Html.ActionLink("Wypożycz", "Login", "Home", new { carId = Model.CarID }, new { @class = "pull-right btn btn-default btn-xs" })
        }<br />
        <span class="pull-right label label-success">Dostępny</span>

    }
</h3>
<p><span class="info">Cena: @Model.PricePerDay.ToString("c") Rok produkcji: @Model.Year r. Przebieg: @Model.Mileage Pojemność: @Model.Capacity</span></p>

 </div>

CarHire.WebUI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet"
          href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div data-role="page" id="page1">
        <div data-theme="a" data-role="header" data-position="fixed">
            <a class="navbar-brand" href="~/">
                <h3>Wypożyczalnia somochodów</h3>
                </a>
                @if (Session["LogedUserID"] != null)
            {
                    @Html.ActionLink("Wyloguj", "Logout", "Home", null, new { @class = "pull-right label label-danger" })
                }
                else {
                    @Html.ActionLink("Rejestracja", "SignIn", "Users", null, new { @class = "pull-right label label-info" })
                    @Html.ActionLink("Logowanie", "Login", "Home", null, new { @class = "pull-right label label-success" })
                }
                @Html.Action("Menu", "Nav")
                
</div>
        <div data-role="content">
            <ul data-role="listview" data-divider-theme="b" data-inset="false">
                @RenderBody()
            </ul>
        </div>
    </div>
</body>
</html>

CarHire.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title>@ViewBag.Title</title>
    <style>
        .navbar-right{
            float: right !important;
            margin-right: 15px;
            margin-left: 15px;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="~/">
        <span class="hidden-xs">Wypożyczalnia samochodowa</span>
        <div class="visible-xs">Wypożyczalnia</div>
        <div class="visible-xs">samochodowa</div>
        </a>
          @if (Session["LogedUserID"] != null)
        {
            @Html.ActionLink("Wyloguj", "Logout", "Home", null, new { @class = "pull-right label label-danger" })
        }
        else {
        @Html.ActionLink("Rejestracja", "SignIn", "Users", null, new { @class = "pull-right label label-info" })
        @Html.ActionLink("Logowanie", "Login", "Home", null, new { @class = "pull-right label label-success" })
        }
    </div>
    <div class="row panel">
        <div id="categories" class="col-xs-3">
            @Html.Action("Menu","Nav")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>